-- MySQL Script generated by MySQL Workbench
-- Wed 06 Apr 2016 10:16:49 BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema expense
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `expense` ;

-- -----------------------------------------------------
-- Schema expense
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expense` DEFAULT CHARACTER SET utf8 ;
USE `expense` ;

-- -----------------------------------------------------
-- Table `expense`.`expense_root_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expense`.`expense_root_account` ;

CREATE TABLE IF NOT EXISTS `expense`.`expense_root_account` (
  `account_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `date_created` DATE NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `fk_root_account_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `expense`.`expense_client_logins` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `expense`.`expense_client_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expense`.`expense_client_users` ;

CREATE TABLE IF NOT EXISTS `expense`.`expense_client_users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `root_account_id` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `date_created` DATE NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_client_users_1_idx` (`root_account_id` ASC),
  CONSTRAINT `fk_client_users_1`
    FOREIGN KEY (`root_account_id`)
    REFERENCES `expense`.`expense_root_account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `expense`.`expense_client_logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expense`.`expense_client_logins` ;

CREATE TABLE IF NOT EXISTS `expense`.`expense_client_logins` (
  `login_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `auth_key` VARCHAR(255) NOT NULL,
  `secret` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`login_id`),
  INDEX `user_key_idx` (`user_id` ASC),
  CONSTRAINT `user_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `expense`.`expense_client_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `expense`.`expense_receipt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expense`.`expense_receipt` ;

CREATE TABLE IF NOT EXISTS `expense`.`expense_receipt` (
  `receipt_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `notes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`receipt_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `expense`.`expense_client_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `expense`.`expense_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expense`.`expense_items` ;

CREATE TABLE IF NOT EXISTS `expense`.`expense_items` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `receipt_id` INT(11) NOT NULL,
  `item_name` VARCHAR(255) NOT NULL,
  `item_price` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`, `receipt_id`),
  INDEX `fk_items_1_idx` (`receipt_id` ASC),
  CONSTRAINT `fk_items_1`
    FOREIGN KEY (`receipt_id`)
    REFERENCES `expense`.`expense_receipt` (`receipt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `expense`.`expense_password_reset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expense`.`expense_password_reset` ;

CREATE TABLE IF NOT EXISTS `expense`.`expense_password_reset` (
  `reset_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `reset_token` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`reset_id`),
  UNIQUE INDEX `reset_token_UNIQUE` (`reset_token` ASC),
  INDEX `fk_password_reset_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_password_reset_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `expense`.`expense_client_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_password_reset_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `expense`.`expense_root_account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
